[package]
name = "game-business"
version = "0.1.0"
authors = ["Evolveye <stolarski.paw@gmail.com>"]
edition = "2018"

[dependencies]
rand = "^0.7.3"
hyper="0.13"
tokio = { version = "0.2", features = ["full"] }
futures = "0.3"
mime = "0.3.16"